// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pustok_Backend.Data;

#nullable disable

namespace Pustok_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240113162617_addedTestimonialTableAndItsData")]
    partial class addedTestimonialTableAndItsData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Pustok_Backend.Models.Advert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Adverts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3915),
                            Image = "promo-banner-with-text.webp",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3915)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3917),
                            Image = "promo-banner-with-text-2.webp",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3917)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3918),
                            Header = "Buy 3. Get Free 1.",
                            Image = "promo-banner-mid.webp",
                            SoftDeleted = false,
                            Title = "50% off for selected products in Pustok.",
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3918)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3919),
                            Header = "$26.00",
                            Image = "promo-banner-small.webp",
                            SoftDeleted = false,
                            Title = "Praise for The Night Child",
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3919)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3920),
                            Header = "I Love This Idea!",
                            Image = "promo-banner-full.webp",
                            SoftDeleted = false,
                            Title = "Cover up front of book and leave summary",
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3921)
                        });
                });

            modelBuilder.Entity("Pustok_Backend.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRememberMe")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Pustok_Backend.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3930),
                            Image = "brand-1.webp",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3930)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3931),
                            Image = "brand-2.webp",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3931)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3932),
                            Image = "brand-3.webp",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3932)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3933),
                            Image = "brand-4.webp",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3933)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3934),
                            Image = "brand-5.webp",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3934)
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3935),
                            Image = "brand-6.webp",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3935)
                        });
                });

            modelBuilder.Entity("Pustok_Backend.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3984),
                            Email = "fidanbb@code.edu.az",
                            Message = "Helllooo",
                            Name = "Fidan Bashirova",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3984)
                        });
                });

            modelBuilder.Entity("Pustok_Backend.Models.Direction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Directions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "right"
                        },
                        new
                        {
                            Id = 2,
                            Name = "left"
                        });
                });

            modelBuilder.Entity("Pustok_Backend.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3899),
                            Description = "Orders over $500",
                            IconName = "fas fa-shipping-fast",
                            SoftDeleted = false,
                            Title = "Free Shipping Item",
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3899)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3901),
                            Description = "100% money back",
                            IconName = "fas fa-redo-alt",
                            SoftDeleted = false,
                            Title = "Money Back Guarantee",
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3901)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3902),
                            Description = "Lorem ipsum dolor amet",
                            IconName = "fas fa-piggy-bank",
                            SoftDeleted = false,
                            Title = "Cash On Delivery",
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3903)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3903),
                            Description = "Call us : + 0123.4567.89",
                            IconName = "fas fa-life-ring",
                            SoftDeleted = false,
                            Title = "Help & Support",
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3904)
                        });
                });

            modelBuilder.Entity("Pustok_Backend.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3944),
                            Key = "HeaderLogo",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3944),
                            Value = "logo.webp"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3946),
                            Key = "FooterLogo",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3947),
                            Value = "logo--footer.webp"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3947),
                            Key = "Address",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3948),
                            Value = "7/135 Saint St. London"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3948),
                            Key = "Phone",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3949),
                            Value = "+18088 234 5678"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3950),
                            Key = "Email",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3951),
                            Value = "support@hastech.com"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3951),
                            Key = "PaymentMethod",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3952),
                            Value = "payment.webp"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3952),
                            Key = "Address2",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3953),
                            Value = "1130/5 Louis III St. New York"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3953),
                            Key = "Phone2",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3954),
                            Value = "+18088 625 4251"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3954),
                            Key = "Email2",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3955),
                            Value = "info@lawyersattorneys.com"
                        });
                });

            modelBuilder.Entity("Pustok_Backend.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DirectionId")
                        .HasColumnType("int");

                    b.Property<string>("Header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DirectionId");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3754),
                            Description = " Cover Up Front Of Books and Leave Summary",
                            DirectionId = 1,
                            Header = "J.D. Kurtness",
                            Image = "home-slider-1-ai.webp",
                            SoftDeleted = false,
                            Title = "De Vengeance",
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3765)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3769),
                            Description = "Cover Up Front Of Books and Leave Summary",
                            DirectionId = 2,
                            Header = "H.G. Wells",
                            Image = "home-slider-2-ai.webp",
                            SoftDeleted = false,
                            Title = "De Vengeance",
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3770)
                        });
                });

            modelBuilder.Entity("Pustok_Backend.Models.Social", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IconName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Socials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3964),
                            IconName = "fa-brands fa-facebook-f",
                            Link = "https://www.facebook.com/",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3964)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3965),
                            IconName = "fa-brands fa-twitter",
                            Link = "https://twitter.com/",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3965)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3966),
                            IconName = "fa-brands fa-google",
                            Link = "https://www.google.com/",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3967)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3967),
                            IconName = "fa-brands fa-youtube",
                            Link = "https://www.youtube.com/",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3968)
                        });
                });

            modelBuilder.Entity("Pustok_Backend.Models.Subscribe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Subscribes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3976),
                            Email = "surac@gmail.com",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3976)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3977),
                            Email = "kubra@gmail.com",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3977)
                        });
                });

            modelBuilder.Entity("Pustok_Backend.Models.Testimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Review")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Testimonials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = "0efd01de-4eec-45ff-9de4-f03f9abdf104",
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3992),
                            Review = " Discovered Pustok, a reader's paradise! Vast collection caters to every literary taste. User-friendly interface made browsing a delight. Quick shipping, excellent customer service – my go-to online bookstore.",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3992)
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = "122ee49a-1c09-45ba-a6a5-4e94b3be7c85",
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3994),
                            Review = "Explored numerous online bookstores, but this one stands out. Curated selection, easy navigation – a reader's haven. Intuitive layout, discover new titles effortlessly. Timely delivery, well-packaged books – highly recommended satisfaction!.",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3994)
                        },
                        new
                        {
                            Id = 3,
                            AppUserId = "4e8b3ae2-4358-4d32-8fdf-d9a95df929e7",
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3995),
                            Review = "Exceeded expectations, Pustok website. Robust search functionality, find what I wanted easily. Seamless checkout process, orders arrive promptly. Attention to detail, quality service keeps me coming back for more literary treasures.",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3996)
                        },
                        new
                        {
                            Id = 4,
                            AppUserId = "8dce53a3-4394-46c3-8ebd-dbb06801e22e",
                            CreatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3996),
                            Review = "Can't say enough good things about Pustok! Vast array of genres, inclusion of hard-to-find titles. Aesthetically pleasing and highly functional design. Orders accurate, well-packaged, delivered on time – a gem in online book retail!",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 13, 20, 26, 17, 489, DateTimeKind.Local).AddTicks(3997)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Pustok_Backend.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Pustok_Backend.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pustok_Backend.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Pustok_Backend.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pustok_Backend.Models.Slider", b =>
                {
                    b.HasOne("Pustok_Backend.Models.Direction", "Direction")
                        .WithMany("Sliders")
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direction");
                });

            modelBuilder.Entity("Pustok_Backend.Models.Testimonial", b =>
                {
                    b.HasOne("Pustok_Backend.Models.AppUser", "AppUser")
                        .WithMany("Testimonials")
                        .HasForeignKey("AppUserId");

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Pustok_Backend.Models.AppUser", b =>
                {
                    b.Navigation("Testimonials");
                });

            modelBuilder.Entity("Pustok_Backend.Models.Direction", b =>
                {
                    b.Navigation("Sliders");
                });
#pragma warning restore 612, 618
        }
    }
}
