// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pustok_Backend.Data;

#nullable disable

namespace Pustok_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240110115305_addedSocialTableAndItsSeededData")]
    partial class addedSocialTableAndItsSeededData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Pustok_Backend.Models.Advert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Adverts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7854),
                            Image = "promo-banner-with-text.webp",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7855)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7856),
                            Image = "promo-banner-with-text-2.webp",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7857)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7858),
                            Header = "Buy 3. Get Free 1.",
                            Image = "promo-banner-mid.webp",
                            SoftDeleted = false,
                            Title = "50% off for selected products in Pustok.",
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7858)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7860),
                            Header = "$26.00",
                            Image = "promo-banner-small.webp",
                            SoftDeleted = false,
                            Title = "Praise for The Night Child",
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7860)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7862),
                            Header = "I Love This Idea!",
                            Image = "promo-banner-full.webp",
                            SoftDeleted = false,
                            Title = "Cover up front of book and leave summary",
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7862)
                        });
                });

            modelBuilder.Entity("Pustok_Backend.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRememberMe")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Pustok_Backend.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7877),
                            Image = "brand-1.webp",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7877)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7919),
                            Image = "brand-2.webp",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7919)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7921),
                            Image = "brand-3.webp",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7921)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7922),
                            Image = "brand-4.webp",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7923)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7924),
                            Image = "brand-5.webp",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7924)
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7925),
                            Image = "brand-6.webp",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7926)
                        });
                });

            modelBuilder.Entity("Pustok_Backend.Models.Direction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Directions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "right"
                        },
                        new
                        {
                            Id = 2,
                            Name = "left"
                        });
                });

            modelBuilder.Entity("Pustok_Backend.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7831),
                            Description = "Orders over $500",
                            IconName = "fas fa-shipping-fast",
                            SoftDeleted = false,
                            Title = "Free Shipping Item",
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7831)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7833),
                            Description = "100% money back",
                            IconName = "fas fa-redo-alt",
                            SoftDeleted = false,
                            Title = "Money Back Guarantee",
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7834)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7836),
                            Description = "Lorem ipsum dolor amet",
                            IconName = "fas fa-piggy-bank",
                            SoftDeleted = false,
                            Title = "Cash On Delivery",
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7836)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7838),
                            Description = "Call us : + 0123.4567.89",
                            IconName = "fas fa-life-ring",
                            SoftDeleted = false,
                            Title = "Help & Support",
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7838)
                        });
                });

            modelBuilder.Entity("Pustok_Backend.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7943),
                            Key = "HeaderLogo",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7944),
                            Value = "logo.webp"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7945),
                            Key = "FooterLogo",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7946),
                            Value = "logo--footer.webp"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7947),
                            Key = "Address",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7948),
                            Value = "Example Street 98, HH2 BacHa, New York, USA"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7949),
                            Key = "Phone",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7949),
                            Value = "+18088 234 5678"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7951),
                            Key = "Email",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7951),
                            Value = "support@hastech.com"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7952),
                            Key = "PaymentMethod",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7953),
                            Value = "payment.webp"
                        });
                });

            modelBuilder.Entity("Pustok_Backend.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DirectionId")
                        .HasColumnType("int");

                    b.Property<string>("Header")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DirectionId");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7641),
                            Description = " Cover Up Front Of Books and Leave Summary",
                            DirectionId = 1,
                            Header = "J.D. Kurtness",
                            Image = "home-slider-1-ai.webp",
                            SoftDeleted = false,
                            Title = "De Vengeance",
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7651)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7655),
                            Description = "Cover Up Front Of Books and Leave Summary",
                            DirectionId = 2,
                            Header = "H.G. Wells",
                            Image = "home-slider-2-ai.webp",
                            SoftDeleted = false,
                            Title = "De Vengeance",
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7656)
                        });
                });

            modelBuilder.Entity("Pustok_Backend.Models.Social", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IconName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Socials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7967),
                            IconName = "fa-brands fa-facebook-f",
                            Link = "https://www.facebook.com/",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7968)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7970),
                            IconName = "fa-brands fa-twitter",
                            Link = "https://twitter.com/",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7970)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7972),
                            IconName = "fa-brands fa-google",
                            Link = "https://www.google.com/",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7972)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7973),
                            IconName = "fa-brands fa-youtube",
                            Link = "https://www.youtube.com/",
                            SoftDeleted = false,
                            UpdatedDate = new DateTime(2024, 1, 10, 15, 53, 4, 337, DateTimeKind.Local).AddTicks(7974)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Pustok_Backend.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Pustok_Backend.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pustok_Backend.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Pustok_Backend.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pustok_Backend.Models.Slider", b =>
                {
                    b.HasOne("Pustok_Backend.Models.Direction", "Direction")
                        .WithMany("Sliders")
                        .HasForeignKey("DirectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direction");
                });

            modelBuilder.Entity("Pustok_Backend.Models.Direction", b =>
                {
                    b.Navigation("Sliders");
                });
#pragma warning restore 612, 618
        }
    }
}
